<?php
/**
 * Created by PhpStorm.
 * User: Antoan Popov <antoanpopoff@gmail.com>
 * Date: 9.10.2017 г.
 * Time: 16:39
 */

namespace Modules\Dashboard\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EditorsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('dashboard_editors')->insert([
                ['id' => '1', 'name' => '--- no editor ---', 'email' => '', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => NULL, 'min_charge' => NULL, 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => '', 'role' => NULL, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'), 'created_by' => 1],
                ['id' => '34', 'name' => 'Renate Walsh', 'email' => 'renate.walsh@renatewalsh.com', 'telephone' => '+44 (0) 1273 967 030', 'mobile' => '+447903577707', 'skype' => 'renate.walsh3', 'time_zone' => 'GMT', 'rate' => '25 GBP', 'min_charge' => '', 'score' => '8', 'experience' => '5', 'notes' => 'Last job TT4578
very good

http://www.renatewalsh.com/', 'color' => 'red', 'role' => 1, 'created_at' => '2014-11-27 07:17:46', 'updated_at' => '2017-05-09 13:12:49', 'created_by' => 1],
                ['id' => '37', 'name' => 'Idlir Shkurti', 'email' => 'idlirshkurti@gmail.com', 'telephone' => '', 'mobile' => '00355682029063', 'skype' => 'ididusha', 'time_zone' => 'GMT +2', 'rate' => '30 euro', 'min_charge' => '', 'score' => '11', 'experience' => '2', 'notes' => '', 'color' => 'red', 'role' => 1, 'created_at' => '2014-11-28 12:48:30', 'updated_at' => '2017-03-28 13:12:32', 'created_by' => 1],
                ['id' => '41', 'name' => 'Trevor Pettit', 'email' => 'trevor_pettit@hotmail.com', 'telephone' => '+44 208 894 6536', 'mobile' => '+44 7533 717 702', 'skype' => '', 'time_zone' => 'GMT', 'rate' => '30 GBP', 'min_charge' => '', 'score' => '17', 'experience' => '5', 'notes' => 'I will be available to work again from 10 July 2017.', 'color' => 'green', 'role' => 1, 'created_at' => '2014-12-01 08:36:56', 'updated_at' => '2017-06-30 09:50:11', 'created_by' => 1],
                ['id' => '42', 'name' => 'Mark Miller', 'email' => 'mark.miller.translation@gmail.com', 'telephone' => '+1 858 7298679', 'mobile' => '', 'skype' => 'mark.miller.41', 'time_zone' => 'GMT-8', 'rate' => '30 euro', 'min_charge' => '', 'score' => '8', 'experience' => '3', 'notes' => 'Great quality
I will be happy to take this and future jobs on for €0.06/source word or €60/1000 words.', 'color' => 'red', 'role' => 1, 'created_at' => '2014-12-01 08:39:24', 'updated_at' => '2017-05-09 13:12:56', 'created_by' => 1],
                ['id' => '43', 'name' => 'Tadeja Prosen', 'email' => 'tadotado@mail.com', 'telephone' => '00436506685956', 'mobile' => '', 'skype' => '', 'time_zone' => 'GMT+1', 'rate' => '30 euro', 'min_charge' => '', 'score' => '14', 'experience' => '2', 'notes' => 'Needs to be constantly checked
Bad feedback on TT10111', 'color' => 'green', 'role' => 1, 'created_at' => '2014-12-01 08:43:21', 'updated_at' => '2017-09-04 11:10:40', 'created_by' => 1],
                ['id' => '45', 'name' => 'Conor Sinclair', 'email' => 'conorsinclair@hotmail.com', 'telephone' => '44 2890589211', 'mobile' => '44 7540761620', 'skype' => '44 2890589211', 'time_zone' => 'GMT', 'rate' => '25 GBP', 'min_charge' => '', 'score' => '13', 'experience' => '2', 'notes' => '', 'color' => 'green', 'role' => 1, 'created_at' => '2014-12-01 08:52:10', 'updated_at' => '2014-12-01 09:09:24', 'created_by' => 1],
                ['id' => '46', 'name' => 'Silke Harvey', 'email' => 's.harveytranslations@yahoo.co.uk', 'telephone' => '', 'mobile' => '+44 (0)7851 972393', 'skype' => 's.harveytranslations', 'time_zone' => 'GMT', 'rate' => '60 GBP', 'min_charge' => '', 'score' => '6', 'experience' => '3', 'notes' => 'PT1931 and PT1935', 'color' => 'red', 'role' => 2, 'created_at' => '2014-12-01 08:56:10', 'updated_at' => '2015-11-27 09:11:03', 'created_by' => 1],
                ['id' => '47', 'name' => 'Nicola Holmes', 'email' => 'nicola@sunriselanguageservices.co.uk', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => 'GMT', 'rate' => '25 GBP', 'min_charge' => '', 'score' => '16', 'experience' => '3', 'notes' => 'I would just like to let you know that I will be out of the office on 15,
18, 19 September and 2-21 November.', 'color' => 'green', 'role' => 1, 'created_at' => '2014-12-01 09:01:47', 'updated_at' => '2017-09-08 07:04:01', 'created_by' => 1],
                ['id' => '48', 'name' => 'Kit Guichard', 'email' => 'kitguichard@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => 'GMT+1', 'rate' => '25 GBP', 'min_charge' => '', 'score' => '10', 'experience' => '2', 'notes' => '', 'color' => 'red', 'role' => 1, 'created_at' => '2014-12-01 09:04:34', 'updated_at' => '2017-03-24 13:53:17', 'created_by' => 1],
                ['id' => '50', 'name' => 'Liliana Ionescu', 'email' => 'liliana.ionescu@prolangue.fr', 'telephone' => '033 09 55 21 53 20', 'mobile' => '033 06 29 05 63 07', 'skype' => '', 'time_zone' => 'GMT+1', 'rate' => '30 euro', 'min_charge' => '', 'score' => '14', 'experience' => '5', 'notes' => 'Very reliable
I\'m available until October 7th and then from the 20th', 'color' => 'green', 'role' => 1, 'created_at' => '2014-12-01 09:08:00', 'updated_at' => '2016-09-28 06:47:27', 'created_by' => 1],
                ['id' => '51', 'name' => 'Sylvia Deckers', 'email' => 'sylviadeckers@wanadoo.fr', 'telephone' => '0031648654913', 'mobile' => '0033565422326', 'skype' => 'youareinthetwilightzone', 'time_zone' => 'GMT+1', 'rate' => '30 euro', 'min_charge' => '', 'score' => '12', 'experience' => '3', 'notes' => 'Dutch is better than French', 'color' => 'red', 'role' => 1, 'created_at' => '2014-12-01 09:11:20', 'updated_at' => '2017-07-26 13:24:26', 'created_by' => 1],
                ['id' => '52', 'name' => 'Kelly Venz', 'email' => 'kvtranslations@hotmail.com', 'telephone' => '', 'mobile' => '', 'skype' => 'jc119007', 'time_zone' => 'GMT+1', 'rate' => '30 euro', 'min_charge' => '', 'score' => '10', 'experience' => '1', 'notes' => '', 'color' => 'red', 'role' => 1, 'created_at' => '2014-12-01 09:14:16', 'updated_at' => '2017-03-24 13:52:43', 'created_by' => 1],
                ['id' => '53', 'name' => 'Yvonne Gallagher', 'email' => 'yvonneg06@yahoo.co.uk', 'telephone' => '00353879631838', 'mobile' => '', 'skype' => 'yvonne.gallagher22', 'time_zone' => 'GMT', 'rate' => '30 euro', 'min_charge' => '', 'score' => '10', 'experience' => '2', 'notes' => 'French is ok, use Spanish as last option', 'color' => 'red', 'role' => 1, 'created_at' => '2014-12-01 09:33:27', 'updated_at' => '2017-03-28 13:11:53', 'created_by' => 1],
                ['id' => '54', 'name' => 'Hannah Gunasingh', 'email' => 'goldenbead101@gmail.com', 'telephone' => '91-80-25451260', 'mobile' => '91-9986786988', 'skype' => 'hgunasingh', 'time_zone' => 'GMT+5.5', 'rate' => '30 euro', 'min_charge' => '', 'score' => '8', 'experience' => '1', 'notes' => 'Hopeless', 'color' => 'red', 'role' => 1, 'created_at' => '2014-12-01 09:44:45', 'updated_at' => '2017-03-24 10:09:04', 'created_by' => 1],
                ['id' => '57', 'name' => 'Rick Copeland', 'email' => 'rick.copeland.10@gmail.com', 'telephone' => '+1 (403) 770-9265', 'mobile' => '', 'skype' => 'rick.copeland.10', 'time_zone' => 'GMT -7', 'rate' => '30 GBP', 'min_charge' => '', 'score' => '15', 'experience' => '3', 'notes' => '', 'color' => 'green', 'role' => 1, 'created_at' => '2014-12-03 08:41:24', 'updated_at' => '2014-12-03 08:41:46', 'created_by' => 1],
                ['id' => '58', 'name' => 'Maureen Wilkins', 'email' => 'maureen.wilkins@ntlworld.com', 'telephone' => '+44 20 8300 1297', 'mobile' => '07946702433', 'skype' => 'mo_monaco', 'time_zone' => 'GMT +1', 'rate' => '30 GBP', 'min_charge' => '', 'score' => '17', 'experience' => '15', 'notes' => 'give her only relaxed jobs', 'color' => 'green', 'role' => 1, 'created_at' => '2014-12-03 08:53:36', 'updated_at' => '2017-03-24 09:55:58', 'created_by' => 1],
                ['id' => '59', 'name' => 'Maria Burnett', 'email' => 'mariab22summit@roadrunner.com', 'telephone' => '011 716 838-3676', 'mobile' => '011 716 445-9327', 'skype' => 'mariab6099', 'time_zone' => 'GMT -7', 'rate' => '40 USD', 'min_charge' => '', 'score' => '14', 'experience' => '3', 'notes' => 'give her only small relaxed jobs', 'color' => 'green', 'role' => 1, 'created_at' => '2014-12-03 09:00:11', 'updated_at' => '2017-03-24 10:06:16', 'created_by' => 1],
                ['id' => '60', 'name' => 'Simon Dix', 'email' => 'simon.dix@mac.com', 'telephone' => '+44 123 241924', 'mobile' => '+44 7850453616', 'skype' => 'simondix', 'time_zone' => 'GMT +1', 'rate' => '25 GBP', 'min_charge' => '', 'score' => '18', 'experience' => '3', 'notes' => 'I\'m on vacation until the 27.09', 'color' => 'green', 'role' => 1, 'created_at' => '2014-12-03 09:03:59', 'updated_at' => '2016-09-14 14:33:04', 'created_by' => 1],
                ['id' => '61', 'name' => 'Paul Norlen', 'email' => 'norlen@mindspring.com', 'telephone' => '1-206-853-8828', 'mobile' => '1-206-853-8828', 'skype' => 'prnorlen', 'time_zone' => 'GMT -7', 'rate' => '25 GBP', 'min_charge' => '', 'score' => '10', 'experience' => '3', 'notes' => '', 'color' => 'red', 'role' => 1, 'created_at' => '2014-12-03 09:07:12', 'updated_at' => '2017-03-28 13:13:29', 'created_by' => 1],
                ['id' => '62', 'name' => 'Andrew Benson', 'email' => 'andrewwilliambenson@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '25 GBP', 'min_charge' => '', 'score' => '9', 'experience' => '3', 'notes' => '', 'color' => 'red', 'role' => 1, 'created_at' => '2014-12-03 09:12:27', 'updated_at' => '2017-03-24 10:22:28', 'created_by' => 1],
                ['id' => '63', 'name' => 'Mark Pallant Tripp', 'email' => 'marcustripp94@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => 'GMT +2', 'rate' => '25 GBP', 'min_charge' => '', 'score' => '15', 'experience' => '3', 'notes' => 'he is keen to work for us more after Sept 26', 'color' => 'green', 'role' => 1, 'created_at' => '2014-12-03 09:16:40', 'updated_at' => '2016-09-09 06:56:29', 'created_by' => 1],
                ['id' => '64', 'name' => 'Jacob Cuttler', 'email' => 'jacob.cuttler@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => 'GMT -5', 'rate' => '45 USD', 'min_charge' => '', 'score' => '5', 'experience' => '3', 'notes' => 'I do not take post-editing jobs anymore.', 'color' => 'red', 'role' => 1, 'created_at' => '2014-12-03 09:32:46', 'updated_at' => '2017-03-28 13:10:26', 'created_by' => 1],
                ['id' => '65', 'name' => 'Mirona Moraru', 'email' => 'MoraruM@cardiff.ac.uk', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => 'GMT +2', 'rate' => '25 GBP', 'min_charge' => '', 'score' => '7', 'experience' => '2', 'notes' => 'Not a freelancer any longer', 'color' => 'red', 'role' => 1, 'created_at' => '2014-12-03 09:36:27', 'updated_at' => '2017-06-27 13:11:59', 'created_by' => 1],
                ['id' => '66', 'name' => 'Dave Harding', 'email' => 'hardingtranslation@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '30 EURO', 'min_charge' => '', 'score' => '10', 'experience' => '1', 'notes' => '', 'color' => 'red', 'role' => 1, 'created_at' => '2014-12-03 11:37:31', 'updated_at' => '2017-03-24 13:51:07', 'created_by' => 1],
                ['id' => '68', 'name' => 'Rod Little', 'email' => 'language_25@yahoo.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '25 GBP', 'min_charge' => '', 'score' => '9', 'experience' => '2', 'notes' => '', 'color' => 'red', 'role' => 1, 'created_at' => '2014-12-04 11:08:47', 'updated_at' => '2017-03-24 13:54:51', 'created_by' => 1],
                ['id' => '69', 'name' => 'Elizabeth Childs-Clarke', 'email' => 'enigmatrans@aol.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '30 euro', 'min_charge' => '', 'score' => '9', 'experience' => '1', 'notes' => '', 'color' => 'red', 'role' => 1, 'created_at' => '2014-12-04 11:11:17', 'updated_at' => '2017-03-24 13:52:54', 'created_by' => 1],
                ['id' => '70', 'name' => 'Mireille Ruepert', 'email' => 'mireilleruepert@hotmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '30 euro', 'min_charge' => '', 'score' => '11', 'experience' => NULL, 'notes' => '', 'color' => 'red', 'role' => 1, 'created_at' => '2014-12-04 11:12:34', 'updated_at' => '2017-04-27 06:57:59', 'created_by' => 1],
                ['id' => '71', 'name' => 'Nienke Brandsma', 'email' => 'nienke_brandsma@hotmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '30 euro', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2014-12-04 11:13:11', 'updated_at' => '2014-12-04 11:13:29', 'created_by' => 1],
                ['id' => '72', 'name' => 'Astrid Homan', 'email' => 'astrid@frontier.net', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '30 euro', 'min_charge' => '', 'score' => '10', 'experience' => NULL, 'notes' => 'I am absolutely still interested! Please let me know what I need to do to proceed.', 'color' => 'darkorange', 'role' => 1, 'created_at' => '2014-12-04 11:14:33', 'updated_at' => '2017-03-29 09:24:28', 'created_by' => 1],
                ['id' => '73', 'name' => 'Tineke Van Beukering', 'email' => 'Tineke@DutchTranslationServices.com.au', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => 'WANTS 35 GBP', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'red', 'role' => 1, 'created_at' => '2014-12-04 11:16:03', 'updated_at' => '2015-11-09 14:05:48', 'created_by' => 1],
                ['id' => '74', 'name' => 'Katja van Hellemond', 'email' => 'katjavanhellemond@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '30 euro', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2014-12-04 11:16:36', 'updated_at' => '2014-12-04 11:17:28', 'created_by' => 1],
                ['id' => '75', 'name' => 'Wiard Sterk', 'email' => 'wiard@urbancondition.co.uk', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '30 euro', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2014-12-04 11:17:08', 'updated_at' => '2014-12-04 11:17:08', 'created_by' => 1],
                ['id' => '76', 'name' => 'Edward Vreeburg', 'email' => 'evreeb@netscape.net', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '30 euro', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2014-12-04 11:18:14', 'updated_at' => '2014-12-04 11:18:14', 'created_by' => 1],
                ['id' => '77', 'name' => 'Lena Maria Clara Vanelslander', 'email' => 'lenavanelslander@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '30 euro', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'green', 'role' => 1, 'created_at' => '2014-12-04 11:19:11', 'updated_at' => '2014-12-23 10:36:00', 'created_by' => 1],
                ['id' => '78', 'name' => 'Larry Farkas', 'email' => 'larryfar@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '30 euro', 'min_charge' => '', 'score' => '14', 'experience' => NULL, 'notes' => '', 'color' => 'green', 'role' => 1, 'created_at' => '2014-12-04 11:20:12', 'updated_at' => '2017-03-28 13:49:44', 'created_by' => 1],
                ['id' => '79', 'name' => 'Kimberlee Thorne', 'email' => 'kwaintraub@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '30 euro', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'darkorange', 'role' => 1, 'created_at' => '2014-12-04 11:21:29', 'updated_at' => '2017-04-06 13:58:36', 'created_by' => 1],
                ['id' => '80', 'name' => 'Kalyani Gadre', 'email' => 'kalyanisgadre@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '30 euro', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2014-12-04 11:22:29', 'updated_at' => '2014-12-04 11:22:29', 'created_by' => 1],
                ['id' => '81', 'name' => 'Palash Mondal', 'email' => 'plsh_mondal@yahoo.co.in', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '30 euro', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2014-12-04 11:23:29', 'updated_at' => '2014-12-04 11:23:29', 'created_by' => 1],
                ['id' => '82', 'name' => 'Camelia Colnic', 'email' => 'cameliacolnic@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '30 GBP', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2014-12-04 11:34:02', 'updated_at' => '2014-12-12 08:56:00', 'created_by' => 1],
                ['id' => '83', 'name' => 'Kathrin Berger', 'email' => 'info@thegermanconnection.co.nz', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '30 euro', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2014-12-04 11:34:36', 'updated_at' => '2014-12-04 11:34:36', 'created_by' => 1],
                ['id' => '84', 'name' => 'David Moore', 'email' => 'scorpiotra@t-online.de', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '30 euro', 'min_charge' => '', 'score' => '9', 'experience' => '1', 'notes' => 'In addition, I felt rather let down by the delay in settlement.', 'color' => 'red', 'role' => 1, 'created_at' => '2014-12-04 11:35:24', 'updated_at' => '2017-03-24 10:11:10', 'created_by' => 1],
                ['id' => '85', 'name' => 'David Tracey', 'email' => 'info@tracey-uebersetzungen.de', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '30 euro', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2014-12-04 11:35:52', 'updated_at' => '2014-12-04 11:35:52', 'created_by' => 1],
                ['id' => '86', 'name' => 'Judith den Otter', 'email' => 'info@den-otter.de', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '30 euro', 'min_charge' => '', 'score' => '9', 'experience' => NULL, 'notes' => '', 'color' => 'red', 'role' => 1, 'created_at' => '2014-12-04 11:36:19', 'updated_at' => '2017-03-28 13:14:00', 'created_by' => 1],
                ['id' => '88', 'name' => 'Roshni', 'email' => 'roshnisahgal@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '30 euro', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2014-12-04 11:37:31', 'updated_at' => '2014-12-04 11:37:31', 'created_by' => 1],
                ['id' => '89', 'name' => 'Davina Bajorek', 'email' => 'davina.bajorek@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '30 euro', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => 'wants 30 GBP', 'color' => 'black', 'role' => 1, 'created_at' => '2014-12-04 11:38:53', 'updated_at' => '2014-12-10 10:45:13', 'created_by' => 1],
                ['id' => '90', 'name' => 'Patricia Buescher', 'email' => 'info@buescher-translations.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => 'GMT +1', 'rate' => '30 euro', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => 'Not doing Legal', 'color' => 'red', 'role' => 1, 'created_at' => '2014-12-04 11:39:59', 'updated_at' => '2017-07-26 13:23:59', 'created_by' => 1],
                ['id' => '91', 'name' => 'Larry Payne', 'email' => 'writerhead@msn.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '30 euro', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'red', 'role' => 1, 'created_at' => '2014-12-04 11:40:48', 'updated_at' => '2017-07-26 13:24:14', 'created_by' => 1],
                ['id' => '92', 'name' => 'Cristina Villanueva', 'email' => 'villa17es@yahoo.es', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '30 euro', 'min_charge' => '', 'score' => '9', 'experience' => NULL, 'notes' => '', 'color' => 'red', 'role' => 1, 'created_at' => '2014-12-04 11:42:01', 'updated_at' => '2017-03-28 13:13:44', 'created_by' => 1],
                ['id' => '93', 'name' => 'Anne Osherson', 'email' => 'anne.osherson@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '30 euro', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2014-12-04 11:42:46', 'updated_at' => '2014-12-04 11:42:46', 'created_by' => 1],
                ['id' => '94', 'name' => 'Elizabeth Mayer', 'email' => 'bjmayer@hotmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '30 euro', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2014-12-04 11:43:23', 'updated_at' => '2014-12-04 11:43:23', 'created_by' => 1],
                ['id' => '95', 'name' => 'Asya', 'email' => 'asya@sokirko.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '30 euro', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'red', 'role' => 1, 'created_at' => '2014-12-04 11:44:59', 'updated_at' => '2014-12-10 10:31:21', 'created_by' => 1],
                ['id' => '96', 'name' => 'Lorenzo Tomasi', 'email' => 'lotoizm@hotmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '30 euro', 'min_charge' => '', 'score' => '15', 'experience' => NULL, 'notes' => 'I will be out of office until Aug 12 2017', 'color' => 'green', 'role' => 1, 'created_at' => '2014-12-04 11:46:39', 'updated_at' => '2017-06-26 12:44:28', 'created_by' => 1],
                ['id' => '97', 'name' => 'Andrew Morris', 'email' => 'morristraduction@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '30 euro', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => 'Excellent. Look forward to hearing from you', 'color' => 'darkorange', 'role' => 1, 'created_at' => '2014-12-04 11:48:39', 'updated_at' => '2017-03-31 12:19:53', 'created_by' => 1],
                ['id' => '98', 'name' => 'Neil Marshall', 'email' => 'neilmarshalltranslates@gmail.com', 'telephone' => '07770 937 012', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '30 euro', 'min_charge' => '', 'score' => '8', 'experience' => NULL, 'notes' => 'wants to be paid upfront', 'color' => 'red', 'role' => 1, 'created_at' => '2014-12-04 11:49:20', 'updated_at' => '2017-03-24 10:09:24', 'created_by' => 1],
                ['id' => '99', 'name' => 'Gabriela Valeria Rodriguez', 'email' => 'gabrielarodriguezc@yahoo.com.ar', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '30 euro', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2014-12-05 08:45:52', 'updated_at' => '2014-12-05 08:45:52', 'created_by' => 1],
                ['id' => '100', 'name' => 'Kimrey A. Hardin Batts', 'email' => 'kimreyanna.linguisticservices@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2014-12-05 08:46:41', 'updated_at' => '2014-12-05 08:46:41', 'created_by' => 1],
                ['id' => '101', 'name' => 'Cesar Serrano', 'email' => 'cesar.serrano1965@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '30 euro', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2014-12-05 08:48:07', 'updated_at' => '2014-12-05 08:48:07', 'created_by' => 1],
                ['id' => '102', 'name' => 'Anthony Baldwin', 'email' => 'baldwinlinguas@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '30 euro', 'min_charge' => '', 'score' => '10', 'experience' => NULL, 'notes' => 'Typically my revision rate (same for PMT) is US$ 0.04/word, which would be more like EU€40/1000 words, but I\'ll give you a shot, 1 project at your offered rate, and assess from there whether I\'ll continue to work for you at that rate.', 'color' => 'darkorange', 'role' => 1, 'created_at' => '2014-12-05 08:49:13', 'updated_at' => '2017-03-29 09:22:28', 'created_by' => 1],
                ['id' => '103', 'name' => 'Anna Lada', 'email' => 'lada@russianbear.net', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '30 euro', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2014-12-05 09:47:34', 'updated_at' => '2014-12-05 09:48:29', 'created_by' => 1],
                ['id' => '104', 'name' => 'Vyacheslav Lomaev', 'email' => 'freelance-translator@yandex.ru', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '30 euro', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2014-12-05 09:48:12', 'updated_at' => '2014-12-05 09:48:12', 'created_by' => 1],
                ['id' => '105', 'name' => 'Lucasz', 'email' => 'lucas.andreski@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '30 euro', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2014-12-05 09:49:55', 'updated_at' => '2014-12-05 09:49:55', 'created_by' => 1],
                ['id' => '106', 'name' => 'Agnieszka Tomeczek', 'email' => 'INFO@TWOWORDSTRANSLATIONS.CO.UK', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '30 euro', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2014-12-05 09:51:28', 'updated_at' => '2015-01-06 10:45:23', 'created_by' => 1],
                ['id' => '107', 'name' => 'Louise Taggart', 'email' => 'louise@translationsabc.co.uk', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '30 euro', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2014-12-10 10:51:44', 'updated_at' => '2014-12-10 10:51:44', 'created_by' => 1],
                ['id' => '108', 'name' => 'Justine Meridith', 'email' => 'judaeda@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '30 GBP', 'min_charge' => '', 'score' => '16', 'experience' => NULL, 'notes' => '', 'color' => 'green', 'role' => 1, 'created_at' => '2014-12-31 09:38:29', 'updated_at' => '2017-03-24 09:58:56', 'created_by' => 1],
                ['id' => '109', 'name' => 'Henry Norreys', 'email' => 'hmwnorreys@hotmail.com', 'telephone' => '+442084323063', 'mobile' => '+442084323063', 'skype' => 'norreysofrycote', 'time_zone' => '', 'rate' => '25 GBP', 'min_charge' => '', 'score' => '1', 'experience' => '5', 'notes' => '', 'color' => 'green', 'role' => 1, 'created_at' => '2015-01-12 07:22:45', 'updated_at' => '2015-01-12 07:22:45', 'created_by' => 1],
                ['id' => '110', 'name' => 'HLT', 'email' => '', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '20', 'experience' => NULL, 'notes' => '', 'color' => 'green', 'role' => 1, 'created_at' => '2015-01-12 08:38:11', 'updated_at' => '2017-04-04 13:51:45', 'created_by' => 1],
                ['id' => '111', 'name' => 'Valmir Guerreiro', 'email' => 'guerreiroguerra@ig.com.br', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '30 euro', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2015-02-09 18:11:02', 'updated_at' => '2015-02-09 18:11:02', 'created_by' => 1],
                ['id' => '112', 'name' => 'Sherin Khullar', 'email' => 'vanillafountain.s@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '35 gbp', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2015-02-09 18:12:41', 'updated_at' => '2015-02-09 18:12:41', 'created_by' => 1],
                ['id' => '113', 'name' => 'Andrew Heath', 'email' => 'heathandrewjohn@yahoo.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '30 euro', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2015-02-09 18:14:04', 'updated_at' => '2015-02-09 18:14:04', 'created_by' => 1],
                ['id' => '114', 'name' => 'CHIARA  BAYLEY', 'email' => 'chiaraelissatorres@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2015-02-10 11:01:19', 'updated_at' => '2015-02-10 11:06:34', 'created_by' => 1],
                ['id' => '115', 'name' => 'Yvonne Gardiner', 'email' => 'yvonne.gardiner@hotmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2015-02-10 11:02:50', 'updated_at' => '2015-02-10 11:05:50', 'created_by' => 1],
                ['id' => '116', 'name' => 'Cynthia Contreras', 'email' => 'cyncontreras@hotmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2015-02-10 11:05:42', 'updated_at' => '2015-02-10 11:05:42', 'created_by' => 1],
                ['id' => '117', 'name' => 'Eric Gerald Mitchell Ort', 'email' => 'erictraductor@yahoo.es', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2015-02-10 11:07:02', 'updated_at' => '2015-02-10 11:07:02', 'created_by' => 1],
                ['id' => '118', 'name' => 'Edward Tully', 'email' => 'edwardtully@hotmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '10', 'experience' => NULL, 'notes' => 'Dear Dani,
thank you for contacting me. I would be interested in post editing for Protext,
but I will not be available until Tuesday next week. I hope this is of some use to you.
kind regards,
Edward Tully', 'color' => 'darkorange', 'role' => 1, 'created_at' => '2015-02-10 11:07:28', 'updated_at' => '2017-03-28 13:10:02', 'created_by' => 1],
                ['id' => '119', 'name' => 'Nicolas Harding', 'email' => 'nicolasharding@hotmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2015-02-10 11:07:57', 'updated_at' => '2015-02-10 11:07:57', 'created_by' => 1],
                ['id' => '120', 'name' => 'Naomi Fillmore', 'email' => 'naomi.fillmore@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2015-02-10 11:08:45', 'updated_at' => '2015-02-10 11:08:45', 'created_by' => 1],
                ['id' => '121', 'name' => 'Martin Phillips', 'email' => 'martin@martinphillips.eu', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '11', 'experience' => NULL, 'notes' => '', 'color' => 'darkorange', 'role' => 1, 'created_at' => '2015-02-10 11:09:09', 'updated_at' => '2017-03-28 14:00:00', 'created_by' => 1],
                ['id' => '122', 'name' => 'Malcolm Shelley', 'email' => 'malcolmshelley62@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '10', 'experience' => NULL, 'notes' => 'Hi Sergei, Sava, and Dani
Dani contacted me this morning and I asked if I was available and willing to post-edit.  I am.  How do we proceed?
Best regards,
Malcolm Shelley', 'color' => 'darkorange', 'role' => 1, 'created_at' => '2015-02-10 11:09:51', 'updated_at' => '2017-03-29 09:23:05', 'created_by' => 1],
                ['id' => '123', 'name' => 'Rajesh Narula', 'email' => 'indobrit@hotmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2015-02-10 11:14:31', 'updated_at' => '2015-02-10 11:14:31', 'created_by' => 1],
                ['id' => '125', 'name' => 'Ally Stack', 'email' => 'ally.stack@yahoo.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2015-02-10 11:16:19', 'updated_at' => '2015-02-10 11:16:19', 'created_by' => 1],
                ['id' => '126', 'name' => 'Rebecca Cockburn', 'email' => 'rebeccacockburn@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '11', 'experience' => NULL, 'notes' => '25GBP/30EUR for 1000 words of target text.', 'color' => 'darkorange', 'role' => 1, 'created_at' => '2015-02-10 11:17:44', 'updated_at' => '2017-03-28 13:59:36', 'created_by' => 1],
                ['id' => '127', 'name' => 'Carol Hart', 'email' => 'carolehrt@yahoo.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2015-02-10 11:20:05', 'updated_at' => '2015-02-10 11:20:05', 'created_by' => 1],
                ['id' => '128', 'name' => 'Rodrigo Maharg Bravo', 'email' => 'info@bravolanguages.net', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2015-02-10 11:20:59', 'updated_at' => '2015-02-10 11:20:59', 'created_by' => 1],
                ['id' => '129', 'name' => 'Sara Maria Hasbun', 'email' => 'saramaria.h@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'red', 'role' => 1, 'created_at' => '2015-02-10 11:22:35', 'updated_at' => '2015-02-12 15:44:36', 'created_by' => 1],
                ['id' => '130', 'name' => 'Dilin Lim', 'email' => 'dilinlim.ie@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2015-02-10 11:23:06', 'updated_at' => '2015-02-10 11:23:06', 'created_by' => 1],
                ['id' => '131', 'name' => 'David Marshland', 'email' => 'dmarshland@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2015-02-10 11:23:34', 'updated_at' => '2015-02-10 11:23:34', 'created_by' => 1],
                ['id' => '132', 'name' => 'Kelly R. Jennemann', 'email' => 'krjennemann@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2015-02-10 11:24:03', 'updated_at' => '2015-02-10 11:24:03', 'created_by' => 1],
                ['id' => '133', 'name' => 'Jason Schrier', 'email' => 'jr8202@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2015-02-10 11:24:53', 'updated_at' => '2015-02-10 11:24:53', 'created_by' => 1],
                ['id' => '134', 'name' => 'Kela Kexel', 'email' => 'kelakexel@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2015-02-10 11:25:33', 'updated_at' => '2015-02-10 11:25:33', 'created_by' => 1],
                ['id' => '135', 'name' => 'Heloisa Dehler', 'email' => 'heloisa.ewing@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2015-02-10 11:26:10', 'updated_at' => '2015-02-10 11:26:10', 'created_by' => 1],
                ['id' => '136', 'name' => 'Alfred Santos', 'email' => 'agsantos3@live.ru', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2015-02-10 11:26:36', 'updated_at' => '2015-02-10 11:26:36', 'created_by' => 1],
                ['id' => '137', 'name' => 'ALVARO SANCHEZ MENDEZ', 'email' => 'sameal5@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2015-02-10 11:26:58', 'updated_at' => '2015-02-10 11:26:58', 'created_by' => 1],
                ['id' => '138', 'name' => 'Claudio Porto Ribeiro', 'email' => 'claudioporto.ribeiro@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2015-02-10 11:27:18', 'updated_at' => '2015-02-10 11:27:18', 'created_by' => 1],
                ['id' => '139', 'name' => 'Telmo Guise', 'email' => 'telmo.carlos.pt@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2015-02-10 11:27:50', 'updated_at' => '2015-02-10 11:27:50', 'created_by' => 1],
                ['id' => '140', 'name' => 'Christopher & Rozilene Frye', 'email' => 'fryestranslations@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2015-02-10 11:28:20', 'updated_at' => '2015-02-10 11:28:20', 'created_by' => 1],
                ['id' => '141', 'name' => 'James Alasdair Fenton', 'email' => 'ali.fenton@globalingua.org', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2015-02-10 11:28:44', 'updated_at' => '2015-02-10 11:28:44', 'created_by' => 1],
                ['id' => '142', 'name' => 'GATHII Andrew Kiriti', 'email' => 'andrekiriti@yahoo.fr', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2015-02-10 11:30:13', 'updated_at' => '2015-02-10 11:30:13', 'created_by' => 1],
                ['id' => '143', 'name' => 'Gwiango Tolo Louis', 'email' => 'tololouis@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2015-02-10 11:30:47', 'updated_at' => '2015-02-10 11:30:47', 'created_by' => 1],
                ['id' => '144', 'name' => 'Phillip North', 'email' => 'pmnorth@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '14', 'experience' => NULL, 'notes' => 'Yes, I\'m still available and willing to post-edit.', 'color' => 'green', 'role' => 1, 'created_at' => '2015-02-10 11:31:08', 'updated_at' => '2017-05-18 06:56:29', 'created_by' => 1],
                ['id' => '145', 'name' => 'John Garside', 'email' => 'jmg@sympatico.ca', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2015-02-10 11:31:30', 'updated_at' => '2015-02-10 11:31:30', 'created_by' => 1],
                ['id' => '146', 'name' => 'Victoria', 'email' => 'faucher.v.a@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => 'Unfortunately, I will not be able to collaborate on this project as the proposed rate is lower than the minimum rate of 60 EUR per 1000 words of target text that I am able to offer.', 'color' => 'red', 'role' => 1, 'created_at' => '2015-02-10 11:31:53', 'updated_at' => '2017-03-29 07:06:12', 'created_by' => 1],
                ['id' => '147', 'name' => 'Tatiana Kochegarova', 'email' => 'translatesb@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2015-02-10 11:32:19', 'updated_at' => '2015-02-10 11:32:19', 'created_by' => 1],
                ['id' => '148', 'name' => 'Michelle Bodle', 'email' => 'michellebodleTS@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2015-02-10 11:32:47', 'updated_at' => '2015-02-10 11:32:47', 'created_by' => 1],
                ['id' => '149', 'name' => 'Akhila Phadnis', 'email' => 'alias.phadnis@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2015-02-10 11:33:12', 'updated_at' => '2015-02-10 11:33:12', 'created_by' => 1],
                ['id' => '150', 'name' => 'James Perry', 'email' => 'jamesfredperry@btinternet.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2015-02-10 11:33:33', 'updated_at' => '2015-02-10 11:33:33', 'created_by' => 1],
                ['id' => '151', 'name' => 'Jyotsna', 'email' => 'jyotsnabhatia2010@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2015-02-10 11:34:21', 'updated_at' => '2015-02-10 11:34:21', 'created_by' => 1],
                ['id' => '152', 'name' => 'Cristiana Karon Letteri', 'email' => 'cristianakaronletteri@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2015-02-10 11:34:54', 'updated_at' => '2015-02-10 11:34:54', 'created_by' => 1],
                ['id' => '153', 'name' => 'Peter Stoev', 'email' => 'peter.stoev@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2015-02-10 11:35:36', 'updated_at' => '2015-02-10 11:35:36', 'created_by' => 1],
                ['id' => '154', 'name' => 'Diana Roman', 'email' => 'rusa.engleza@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2015-02-10 11:35:57', 'updated_at' => '2015-02-10 11:35:57', 'created_by' => 1],
                ['id' => '155', 'name' => 'Kathy Stackhouse', 'email' => 'kathy.stackhouse@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2015-02-10 11:36:14', 'updated_at' => '2015-02-10 11:36:14', 'created_by' => 1],
                ['id' => '156', 'name' => 'Tania Northorpe', 'email' => 'tnorthorpe@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2015-02-10 11:36:31', 'updated_at' => '2015-02-10 11:36:31', 'created_by' => 1],
                ['id' => '157', 'name' => 'Margarita Ehlinger', 'email' => 'taikatranslations@yahoo.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2015-02-10 11:36:54', 'updated_at' => '2015-02-10 11:36:54', 'created_by' => 1],
                ['id' => '158', 'name' => 'OLGA NENAKHOVA', 'email' => 'olga.nenakhova@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2015-02-10 11:37:32', 'updated_at' => '2015-02-10 11:37:32', 'created_by' => 1],
                ['id' => '159', 'name' => 'Adam Fuss', 'email' => 'adam@abftranslations.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2015-02-10 11:37:53', 'updated_at' => '2015-02-10 11:37:53', 'created_by' => 1],
                ['id' => '160', 'name' => 'Michal Lis', 'email' => 'translafox@wp.pl', 'telephone' => '+48 888-900-213', 'mobile' => '', 'skype' => 'skype: translafox', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2015-02-11 16:38:43', 'updated_at' => '2016-07-21 10:35:51', 'created_by' => 1],
                ['id' => '161', 'name' => 'Roger Matthews', 'email' => 'roger@devontranslations.com', 'telephone' => '+44 7813 582273', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '30 GBP', 'min_charge' => '', 'score' => '17', 'experience' => NULL, 'notes' => 'Hugh spoke with him on 07.09.2016. Roger said he is OK to work.

I am basically booked up until the end of May 2017', 'color' => 'green', 'role' => 1, 'created_at' => '2015-09-14 11:23:01', 'updated_at' => '2017-05-23 12:44:04', 'created_by' => 1],
                ['id' => '162', 'name' => 'Romina Yaneva', 'email' => 'rominayaneva@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '10', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2016-03-02 11:52:58', 'updated_at' => '2016-03-02 11:52:58', 'created_by' => 1],
                ['id' => '163', 'name' => 'Xenophiles Limited', 'email' => '', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '20', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2016-03-09 10:47:19', 'updated_at' => '2016-03-09 10:47:19', 'created_by' => 1],
                ['id' => '164', 'name' => 'Wagner Christian', 'email' => 'morethanwords2512@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'green', 'role' => 2, 'created_at' => '2016-04-07 14:09:27', 'updated_at' => '2017-04-12 13:12:16', 'created_by' => 1],
                ['id' => '165', 'name' => 'Legentis', 'email' => 'bgodfrey@legentistranslation.com', 'telephone' => 'T: +44 (0)207 993 8446', 'mobile' => 'M: +44 (0)7538 048 165', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '12', 'experience' => NULL, 'notes' => 'Ben Godfrey | Director

Legentis Translation Ltd.
45 King William Street, London, EC4R 9AN, United Kingdom

T: +44 (0)207 993 8446  M: +44 (0)7538 048 165  F: +44 (0)207 900 2086
bgodfrey@legentistranslation.com | www.legentistranslation.com', 'color' => 'green', 'role' => 2, 'created_at' => '2016-09-01 10:09:31', 'updated_at' => '2016-09-01 10:09:31', 'created_by' => 1],
                ['id' => '166', 'name' => 'Sonia Wichmann', 'email' => 'translate@swichmann.org.', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '12', 'experience' => NULL, 'notes' => 'Thank you for contacting me. Yes, I would be interested in this project and look forward to learning more about it.', 'color' => 'darkorange', 'role' => 1, 'created_at' => '2017-03-21 07:39:34', 'updated_at' => '2017-03-30 06:39:25', 'created_by' => 1],
                ['id' => '167', 'name' => 'CGB Translations', 'email' => 'cb@cgb-translations.com', 'telephone' => '+44 (0)1290 424 453', 'mobile' => '+44 (0)750 401 8148', 'skype' => 'craig_bedworth', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '14', 'experience' => NULL, 'notes' => '', 'color' => 'green', 'role' => 2, 'created_at' => '2017-03-24 11:20:23', 'updated_at' => '2017-03-24 11:20:23', 'created_by' => 1],
                ['id' => '168', 'name' => 'Frances Corry', 'email' => 'francescorry@hotmail.com', 'telephone' => '+44 (0)7939 206903', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '12', 'experience' => NULL, 'notes' => 'still do freelance work on two days per week.', 'color' => 'green', 'role' => 1, 'created_at' => '2017-03-24 13:54:19', 'updated_at' => '2017-04-05 15:07:47', 'created_by' => 1],
                ['id' => '169', 'name' => 'Nik Alatortsev', 'email' => 'nikita.alatortsev@merton.oxon.org', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '14', 'experience' => NULL, 'notes' => 'I could well be interested in doing some work for Translation Team after May 7th 2017', 'color' => 'darkorange', 'role' => 1, 'created_at' => '2017-03-28 13:08:57', 'updated_at' => '2017-04-04 12:39:45', 'created_by' => 1],
                ['id' => '170', 'name' => 'Fiona White', 'email' => 'fiona@dialoguetranslations.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => 'However please do keep my details – that way if you do ever find yourself in desperate need of an Italian/French translator, then you can always get in touch!', 'color' => 'black', 'role' => 1, 'created_at' => '2017-03-29 09:33:58', 'updated_at' => '2017-03-29 09:33:58', 'created_by' => 1],
                ['id' => '171', 'name' => 'Heather Philips', 'email' => 'heather.l.phillips09@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => 'GMT', 'rate' => '', 'min_charge' => '', 'score' => '1', 'experience' => '30', 'notes' => '', 'color' => 'darkorange', 'role' => 1, 'created_at' => '2017-04-04 12:38:44', 'updated_at' => '2017-04-06 12:51:45', 'created_by' => 1],
                ['id' => '172', 'name' => 'David Rumsey', 'email' => 'nordictranslator@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '35', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'black', 'role' => 1, 'created_at' => '2017-04-04 12:41:44', 'updated_at' => '2017-04-06 10:11:00', 'created_by' => 1],
                ['id' => '173', 'name' => 'Rosemary Lawrey', 'email' => 'rose@roundoak.plus.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'green', 'role' => 1, 'created_at' => '2017-04-04 12:43:21', 'updated_at' => '2017-04-04 12:43:21', 'created_by' => 1],
                ['id' => '174', 'name' => 'Christiane Klauss', 'email' => 'christiane.klauss@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => 'GMT +13', 'rate' => 'NZD 0.20/word', 'min_charge' => '', 'score' => '1', 'experience' => '', 'notes' => 'she lives in NZ, she does localisation jobs from UK or US English to NZ English', 'color' => 'black', 'role' => 1, 'created_at' => '2017-04-05 06:23:21', 'updated_at' => '2017-04-05 06:24:25', 'created_by' => 1],
                ['id' => '175', 'name' => 'Helena Lopez', 'email' => 'translationshl@gmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => 'GMT +1', 'rate' => '30 euro', 'min_charge' => '', 'score' => '1', 'experience' => '10', 'notes' => '', 'color' => 'darkorange', 'role' => 1, 'created_at' => '2017-04-05 11:14:51', 'updated_at' => '2017-04-05 11:15:08', 'created_by' => 1],
                ['id' => '176', 'name' => 'Emilia Balke', 'email' => 'ebalke@language-web.net', 'telephone' => '(818) 735-0565', 'mobile' => '(818) 438-6584', 'skype' => 'emilia.balke@gmail.com', 'time_zone' => 'GMT -7', 'rate' => '', 'min_charge' => '', 'score' => '1', 'experience' => '20', 'notes' => '', 'color' => 'red', 'role' => 1, 'created_at' => '2017-04-06 06:17:25', 'updated_at' => '2017-06-20 08:00:08', 'created_by' => 1],
                ['id' => '177', 'name' => 'Stephanie Sewell', 'email' => 'stephaniesewell@yahoo.com', 'telephone' => 'New Zealand', 'mobile' => '', 'skype' => '', 'time_zone' => 'GMT +13', 'rate' => '30gbp or 35 eur', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'darkorange', 'role' => 1, 'created_at' => '2017-04-06 06:27:15', 'updated_at' => '2017-04-06 06:27:15', 'created_by' => 1],
                ['id' => '178', 'name' => 'Ruth Ramsey', 'email' => 'rramsey@essentiallyspanish.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => 'GMT', 'rate' => '27.5GBP', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'darkorange', 'role' => 1, 'created_at' => '2017-04-07 06:08:52', 'updated_at' => '2017-04-11 06:51:34', 'created_by' => 1],
                ['id' => '179', 'name' => 'Louisa Berry', 'email' => 'louisa@deantranslations.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => 'GMT', 'rate' => '', 'min_charge' => '25', 'score' => '1', 'experience' => NULL, 'notes' => 'previously Louisa Fox', 'color' => 'darkorange', 'role' => 1, 'created_at' => '2017-04-24 06:14:55', 'updated_at' => '2017-04-24 06:14:55', 'created_by' => 1],
                ['id' => '180', 'name' => 'Barry Appleby', 'email' => 'baruch1948@gmail.com', 'telephone' => '01323484725', 'mobile' => '', 'skype' => '', 'time_zone' => 'GMT', 'rate' => '25GBP', 'min_charge' => '', 'score' => '1', 'experience' => '20', 'notes' => '', 'color' => 'darkorange', 'role' => 1, 'created_at' => '2017-06-20 13:59:12', 'updated_at' => '2017-06-20 14:01:59', 'created_by' => 1],
                ['id' => '181', 'name' => 'Sandra Kirley', 'email' => 'sandra@naturallynordic.co.uk', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '30 eur/25gbp', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'darkorange', 'role' => 1, 'created_at' => '2017-06-23 09:20:57', 'updated_at' => '2017-06-23 09:20:57', 'created_by' => 1],
                ['id' => '182', 'name' => 'Michael Ellis', 'email' => 'mgmwellis@btinternet.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '25GBP', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => 'let’s start at 2000 words/day to start with
away until 2.07.2017', 'color' => 'darkorange', 'role' => 1, 'created_at' => '2017-06-23 10:52:36', 'updated_at' => '2017-06-26 05:40:51', 'created_by' => 1],
                ['id' => '183', 'name' => 'Naomi Aylott', 'email' => 'naomiaylott@hotmail.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => 'GMT +1', 'rate' => '20GBP', 'min_charge' => '', 'score' => '1', 'experience' => '7', 'notes' => '', 'color' => 'darkorange', 'role' => 1, 'created_at' => '2017-07-13 06:06:09', 'updated_at' => '2017-07-13 06:06:09', 'created_by' => 1],
                ['id' => '184', 'name' => 'Jo Hance', 'email' => 'hancejo@outlook.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => 'GMT', 'rate' => '25GBP', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'darkorange', 'role' => 1, 'created_at' => '2017-07-27 07:50:52', 'updated_at' => '2017-07-27 07:50:52', 'created_by' => 1],
                ['id' => '185', 'name' => 'Peter Simon', 'email' => 'speterkar@yahoo.com', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '30 euro', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'darkorange', 'role' => 1, 'created_at' => '2017-07-27 09:13:40', 'updated_at' => '2017-07-27 09:13:40', 'created_by' => 1],
                ['id' => '186', 'name' => 'Julia Burgess', 'email' => 'julia_burgess@hotmail.co.uk', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => 'I work on "general" business documents (press releases, CSR reports, etc.), texts for the tourism sector and non-technical documents in the field of environmental protection/climate change.', 'color' => 'darkorange', 'role' => 1, 'created_at' => '2017-07-27 09:59:13', 'updated_at' => '2017-07-27 09:59:13', 'created_by' => 1],
                ['id' => '187', 'name' => 'Stephen Old', 'email' => 'stephen.old@blueyonder.co.uk', 'telephone' => '', 'mobile' => '', 'skype' => '', 'time_zone' => '', 'rate' => '25GBP', 'min_charge' => '', 'score' => '1', 'experience' => NULL, 'notes' => '', 'color' => 'darkorange', 'role' => 1, 'created_at' => '2017-07-31 05:59:06', 'updated_at' => '2017-08-01 09:05:18', 'created_by' => 1],
            ]);
    }
}
